/**
 * Radio catalog, static, committed to the repo.
 *
 * Every client derives the same (song, second) from wall-clock time against
 * this data, so nothing here may be fetched at runtime. Durations drive the
 * prefix-sum schedule and must stay in sync with the published videos.
 *
 * Each station's track list lives in its own file under `./stations/`,
 * generated by `scripts/build_radio_station.py` (oEmbed lacks duration, so the
 * script reads it from the YouTube Data API).
 */

import { manifest as bellasManifest } from "./stations/bellas";
import { manifest as d1Manifest } from "./stations/d1";

export interface RadioManifestEntry {
  videoId: string;
  durationSec: number;
  title: string;
  author: string;
  /** Maintainer-confirmed embed-refused; substituted at schedule build. */
  blocked?: boolean;
}

/**
 * A single global evergreen video used to fill any slot whose scheduled track
 * is `blocked`, or that a client finds the embed refusing at runtime (see
 * `unavailableVideos` in the radio controller). Because it is one committed
 * constant, every client substitutes the same slot with the same content, so
 * determinism across devices is preserved.
 *
 * Three properties this entry must have, all of them load-bearing:
 *
 * - **A fixed duration.** A live stream has none to schedule against, never
 *   fires ENDED, and puts every client at a different point in its window for
 *   the same `startSeconds` — which would make the one slot that exists to
 *   keep clients in sync the only one that cannot. This pointed at a 24/7
 *   stream once; the loop kept working only because the tick eventually moved
 *   it on.
 * - **Embeddable.** Every other refusal falls back to it, so if this is
 *   refused too there is nothing left to substitute.
 * - **Absent from MANIFEST.** A slot keys its `Track` off the videoId, so a
 *   fallback that is also scheduled in its own right would appear twice in one
 *   loop under a single id.
 */
export const RADIO_FALLBACK: RadioManifestEntry = {
  videoId: "kJQP7kiw5Fk",
  durationSec: 282,
  title: "Luis Fonsi - Despacito ft. Daddy Yankee",
  author: "LuisFonsiVEVO",
};

/**
 * The default station's rotation, kept as its own export because the tests
 * and the fallback invariants were written against it before stations
 * existed.
 */
export const MANIFEST: RadioManifestEntry[] = d1Manifest;

/** A station's look while no user background is active behind it (legacy view only). */
export interface RadioBackground {
  id: string;
  /** Tailwind classes for a flat/gradient fill, standing in for a real asset. */
  className: string;
}

export interface RadioStation {
  id: string;
  /** Shown on the station display; short, since the screen is one line wide. */
  name: string;
  manifest: RadioManifestEntry[];
  fallback: RadioManifestEntry;
  background: RadioBackground;
}

/**
 * Registry of radio stations, keyed by id.
 *
 * Scheduling/session code is written against this registry rather than the
 * bare `MANIFEST`/`RADIO_FALLBACK` constants, so another station is a new
 * entry here, not a refactor of `schedule.ts`/`position.ts`/`controller.ts`.
 * Nothing in the UI picks a station yet, so only `DEFAULT_RADIO_STATION`
 * is ever tuned; the rest wait for that control.
 */
export const RADIO_STATIONS = {
  d1: {
    id: "d1",
    name: "D1",
    manifest: MANIFEST,
    fallback: RADIO_FALLBACK,
    background: {
      id: "radio-d1",
      className: "bg-gradient-to-b from-surface via-background to-background",
    },
  },
  bellas: {
    id: "bellas",
    name: "BeLLaS",
    manifest: bellasManifest,
    fallback: RADIO_FALLBACK,
    background: {
      id: "radio-bellas",
      className: "bg-gradient-to-b from-background via-surface to-background",
    },
  },
} satisfies Record<string, RadioStation>;

export type RadioStationId = keyof typeof RADIO_STATIONS;

export const DEFAULT_RADIO_STATION: RadioStationId = "d1";

/** Registry order, which is the order the station selector steps through. */
export const RADIO_STATION_IDS = Object.keys(RADIO_STATIONS) as RadioStationId[];

export function isRadioStationId(value: unknown): value is RadioStationId {
  return typeof value === "string" && value in RADIO_STATIONS;
}

/**
 * The station `offset` steps away, wrapping in both directions so a pair of
 * prev/next keys reaches every station however many there are.
 */
export function stationAtOffset(from: RadioStationId, offset: number): RadioStationId {
  const count = RADIO_STATION_IDS.length;
  const index = RADIO_STATION_IDS.indexOf(from);
  return RADIO_STATION_IDS[(((index + offset) % count) + count) % count] ?? DEFAULT_RADIO_STATION;
}
