"""Writes src/radio/stations/<id>.ts in the shape src/radio/manifest.ts imports."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STATIONS_DIR = os.path.join(REPO_ROOT, "src", "radio", "stations")
MANIFEST_TS = os.path.join(REPO_ROOT, "src", "radio", "manifest.ts")
STATION_ID_RE = re.compile(r"[a-z0-9][a-z0-9-]*")
FALLBACK_ID_RE = re.compile(r"RADIO_FALLBACK[^=]*=\s*\{\s*videoId:\s*\"([^\"]+)\"", re.S)


@dataclass(frozen=True)
class Entry:
    video_id: str
    duration_sec: int
    title: str
    author: str
    blocked: bool = False


def validate_station_id(station_id: str) -> str:
    if not STATION_ID_RE.fullmatch(station_id):
        raise SystemExit(f"Station id must be lowercase letters, digits and dashes: {station_id!r}")
    return station_id


def read_fallback_video_id(manifest_path: str = MANIFEST_TS) -> str | None:
    """The fallback must never be scheduled on its own (see RADIO_FALLBACK)."""
    try:
        with open(manifest_path, encoding="utf-8") as f:
            match = FALLBACK_ID_RE.search(f.read())
    except FileNotFoundError:
        return None
    return match.group(1) if match else None


def ts_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    return f'"{escaped}"'


def render(entries: list[Entry], sources: list[str]) -> str:
    lines = [
        'import type { RadioManifestEntry } from "../manifest";',
        "",
        "/**",
        " * Generated by scripts/build_radio_station.py; edits here are overwritten.",
        " * Sources:",
        *[f" *   {source}" for source in sources],
        " */",
        "export const manifest: RadioManifestEntry[] = [",
    ]
    for entry in entries:
        fields = [
            f"videoId: {ts_string(entry.video_id)}",
            f"durationSec: {entry.duration_sec}",
            f"title: {ts_string(entry.title)}",
            f"author: {ts_string(entry.author)}",
        ]
        if entry.blocked:
            fields.append("blocked: true")
        lines.append("  { " + ", ".join(fields) + " },")
    lines.append("];")
    return "\n".join(lines) + "\n"


def write(station_id: str, entries: list[Entry], sources: list[str], out_dir: str = STATIONS_DIR) -> str:
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{station_id}.ts")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(entries, sources))
    return path


ENTRY_RE = re.compile(r'videoId:\s*"([^"]+)",\s*durationSec:\s*\d+,\s*title:\s*"((?:[^"\\]|\\.)*)"')


def read_entries(station_id: str, out_dir: str = STATIONS_DIR) -> dict[str, str]:
    """{videoId: title} of the station as committed, for a before/after diff."""
    try:
        with open(os.path.join(out_dir, f"{station_id}.ts"), encoding="utf-8") as f:
            return {m.group(1): m.group(2).replace('\\"', '"') for m in ENTRY_RE.finditer(f.read())}
    except FileNotFoundError:
        return {}


def describe_changes(before: dict[str, str], after: dict[str, str]) -> list[str]:
    added = [f"+ {title}" for video_id, title in after.items() if video_id not in before]
    removed = [f"- {title}" for video_id, title in before.items() if video_id not in after]
    return removed + added


def is_registered(station_id: str, manifest_path: str = MANIFEST_TS) -> bool:
    """Whether RADIO_STATIONS already imports this station file."""
    try:
        with open(manifest_path, encoding="utf-8") as f:
            return f'from "./stations/{station_id}"' in f.read()
    except FileNotFoundError:
        return False


def registration_hint(station_id: str) -> str:
    identifier = re.sub(r"-(\w)", lambda m: m.group(1).upper(), station_id) + "Manifest"
    return (
        f'If "{station_id}" is new, register it in src/radio/manifest.ts:\n'
        f'  import {{ manifest as {identifier} }} from "./stations/{station_id}";\n'
        f'  "{station_id}": {{ id: "{station_id}", manifest: {identifier}, fallback: RADIO_FALLBACK, background: {{ ... }} }},'
    )
